/** Export Storm client constants */
module.exports = {
  IDEA_CREATE: 'IDEA_CREATE',
  IDEA_GROUP_CREATE: 'IDEA_GROUP_CREATE',
  STORE_MOVED_IDEA: 'STORE_MOVED_IDEA',
  GROUP_IDEAS: 'GROUP_IDEAS',
  DECREASE_TIME: 'DECREASE_TIME',
  STORE_WORKSPACE: 'STORE_WORKSPACE',
};
