/** Export Storm client constants */
module.exports = {
  CHANGE_ROOM_NAME: 'CHANGE_ROOM_NAME',
  IDEA_CREATE: 'IDEA_CREATE',
  TIMER_COUNTDOWN: 'TIMER_COUNTDOWN',
  TIMER_PAUSE: 'TIMER_PAUSE',
  HIDE_IDEAS: 'HIDE_IDEAS',
};
